services:
  proxy:
    volumes:
      - ./configs/nginx_base_conf:/etc/nginx/conf.d/nginx_base_conf:ro
      - ./configs/nginx_https.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
